//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartScheduler.Models.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbAdministator
    {
        public int AdministratorId { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual DbUser User { get; set; }
    }
}
