//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartScheduler.Models.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbAuditory
    {
        public DbAuditory()
        {
            this.ScheduleItems = new HashSet<DbScheduleItem>();
        }
    
        public int AuditoryId { get; set; }
        public int Number { get; set; }
    
        public virtual ICollection<DbScheduleItem> ScheduleItems { get; set; }
    }
}
