//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartScheduler.Models.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbScheduleItem
    {
        public int ScheduleItemId { get; set; }
        public int ScheduleYear { get; set; }
        public Nullable<int> ScheduleId { get; set; }
        public Nullable<int> TeacherId { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<int> AuditoryId { get; set; }
        public Nullable<int> SubjectId { get; set; }
    
        public virtual DbAuditory Auditory { get; set; }
        public virtual DbGroup Group { get; set; }
        public virtual DbSchedule Schedule { get; set; }
        public virtual DbSubject Subject { get; set; }
        public virtual DbTeacher Teacher { get; set; }
    }
}
