//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartScheduler.Models.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbUser
    {
        public DbUser()
        {
            this.Administators = new HashSet<DbAdministator>();
            this.Students = new HashSet<DbStudent>();
            this.Teachers = new HashSet<DbTeacher>();
        }
    
        public int UserId { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public System.DateTime RegDate { get; set; }
        public Nullable<System.DateTime> LastActivityDate { get; set; }
    
        public virtual ICollection<DbAdministator> Administators { get; set; }
        public virtual ICollection<DbStudent> Students { get; set; }
        public virtual ICollection<DbTeacher> Teachers { get; set; }
    }
}
