//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartScheduler.Models.DataContexts
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SmartSchedulerEntities : DbContext
    {
        public SmartSchedulerEntities()
            : base("name=SmartSchedulerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DbAdministator> Administators { get; set; }
        public DbSet<DbAuditory> Auditories { get; set; }
        public DbSet<DbGroup> Groups { get; set; }
        public DbSet<DbRank> Ranks { get; set; }
        public DbSet<DbSchedule> Schedules { get; set; }
        public DbSet<DbScheduleItem> ScheduleItems { get; set; }
        public DbSet<DbStudent> Students { get; set; }
        public DbSet<DbStudentsInGroup> StudentsInGroups { get; set; }
        public DbSet<DbSubject> Subjects { get; set; }
        public DbSet<DbTeacher> Teachers { get; set; }
        public DbSet<DbUser> Users { get; set; }
    }
}
